config/routes.rb
Rails.application.routes.draw do

  get 'artículos' => 'articles#index', as: :articles
  get 'articles/show' => 'articles#show' , as: :show_article
  post 'guardar_articulo' => 'articles#create' , as: :create_article
  get 'nuevo' => 'articles#new', as: :new_article
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def new
  	@article = Article.new
  end
  def create
  	@article = Article.new(article_params)
  	@article.save
    respond_to do |format|
      format.html { redirect_to articles_path }
    end
  end

  def show
  end

  private

  def article_params
  	
  	params.require(:article).permit(:titulo, :descripcion, :fecha)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_tag(create_article_path , method: 'post') do %>
	<%= label_tag :titulo, 'titulo'%>
	<%= text_field :article, :titulo %> <br>
	<%= label_tag :descripcion, 'descripcion'%>
	<%= text_field :article, :descripcion %> <br>
	<%= label_tag :fecha, 'fecha'%>
	<%= text_field :article, :fecha %> <br>
	<%= submit_tag 'enviar'%>
<% end %>

app/views/articles/index.html.erb
<h1>mis articulos</h1>
<%= link_to 'nuevo articulo' , new_article_path %>

app/views/articles/new.html.erb
<h1>nuevo articulo</h1>
<%= render 'form' %>
<%= link_to 'volver', root_path %>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articulo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>